### ISSUE TITLE
Warning: Calling plist_options is deprecated!

### ISSUE THREAD

**Issue by aereal** [mackerelio/homebrew-mackerel-agent#39]
> Warning: Calling plist_options is deprecated! Use service.require_root instead.

The above message appears when mackerel-agent formula is evaluated.

The latest `brew services` recognizes two options below:

- installing a service into the formula prefix
- calling `service` method

from https://docs.brew.sh/Formula-Cookbook#service-files

**Comment by kga** [comment]
@aereal We've fixed it! Thank you for your report.
